<Project>
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	<LangVersion>14.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
	<Authors>Mihai Bratulescu</Authors>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	  
	<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' == 'PCompose'">
    <InternalsVisibleTo Include="QChain" />
    <InternalsVisibleTo Include="QChain.EntityFrameworkCore" />
  </ItemGroup>
</Project>
