<Project Sdk="Microsoft.NET.Sdk">

   <ItemGroup>
   	<InternalsVisibleTo Include="QChain.EntityFrameworkCore" />
   </ItemGroup>

   <ItemGroup>
     <Folder Include="NewFolder\" />
   </ItemGroup>

   <PropertyGroup>
     <PackageId>QChain</PackageId>
     <Description>Composable query building library for .NET</Description>
   </PropertyGroup>
	
</Project>